# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
- job: deploy_ASDK
  pool: Default
  steps:
#  - powershell: .\1_getASDKDownloader.ps1 -Verbose
#    displayName:  Get ASDK Downloader
#  - powershell: .\2_copyCloudBuilder.ps1 -ASDKAdminUserPassword $(ASDKAdminUserPassword) -Verbose
#    displayName:  Copy CloudBUilder.vhdx to the Host
#  - powershell: .\3_changeBootDevicetoPhysicalDisks.ps1 -ASDKAdminUserPassword $(ASDKAdminUserPassword) -Verbose
#    displayName:  Change Boot Device to Physical Disks
  - powershell: .\4_prepareASDKHost.ps1 -ASDKAdminUserPassword $(ASDKAdminUserPassword) -Verbose
    displayName:  preparing ASDKHost
  
